float sqrt
Gunivers/Bookshelf pull request #107
Opened 2023-08-27 15:23 UTC by Ethanout

2023-08-27 15:24 UTC, Ethanout reviewed
float sqrt

2023-08-28 08:07 UTC, Leirof requested changes
Missing documentation

2023-08-28 08:07 UTC, Leirof commented on datapacks/Bookshelf/data/bs.math/functions/sqrt/__main__.mcfunction
> +execute if score #check bs.data matches ..-1 run return -1
According to the convention, `#check` should be renamed in `#math.sqrt.check`. Same for the other fake players

2023-08-28 08:07 UTC, Leirof commented on datapacks/Bookshelf/data/bs.math/functions/sqrt/__int__.mcfunction
This feature should be renamed `isqrt` and be place in a separated folder

2023-08-28 08:07 UTC, Leirof commented on datapacks/Bookshelf/data/bs.math/functions/sqrt/__main__.mcfunction
Missing header and the main file should have the same name as the feature, so here `sqrt`

2023-08-28 10:51 UTC, aksiome commented on datapacks/Bookshelf/data/bs.math/functions/sqrt/__int__.mcfunction
I we rename it `isqrt` we also need to round the result to the lowest integer!

2023-09-03 09:20 UTC, Ethanout commented on datapacks/Bookshelf/data/bs.math/functions/sqrt/__main__.mcfunction
hmmm do u mean the __main__.mcfunction should be named as __sqrt__.mcfunction

2023-09-03 09:23 UTC, Leirof commented on datapacks/Bookshelf/data/bs.math/functions/sqrt/__main__.mcfunction
Yep, it's a detail, but as @theogiraudet said, when we are working on several features, having a lot of "main" tabs in VSC is confusing ^^'

2023-09-06 08:06 UTC, Leirof requested changes
Missing documentation

2023-09-06 09:31 UTC, aksiome commented
Please do not merge it into the master branch, i'll merge it myself into the rework of the math module ^^

2023-09-06 16:03 UTC, aksiome commented
Merged into math module rework: #114 😉

2023-09-06 16:03 UTC, closed without merging