Update schedule module
Gunivers/Bookshelf pull request #119
Opened 2023-09-10 17:12 UTC by aksiome

Based on @theogiraudet  PR #118 !
Based on some not very accurate tests (i just used a lot of different random scheduled operation in a loop and compared debug charts) it should be at least 2 times faster, maybe even 3 😁

2023-09-10 17:30 UTC, theogiraudet requested changes
I don't see documentation update

2023-09-10 17:30 UTC, theogiraudet commented on datapacks/Bookshelf/data/bs.schedule/functions/cancel_all.mcfunction
> +# Version: 2.0
The remove_all feature didn't exist before the PR so this is the ﬁrst version if this feature.

2023-09-17 08:05 UTC, Leirof approved these changes

2023-09-17 08:06 UTC, Leirof approved these changes

2023-09-17 08:07 UTC, merged