Fix spread
Gunivers/Bookshelf pull request #41
Opened 2023-03-05 17:18 UTC by A2va

Changements par à l'ancienne version:

* La position Y de l'entité n'est plus conservée maintenant elle se positionnera au dessus de la surface du monde.
* L'entité sera toujours centrée sur le block.

En raison de la première modification, cette fonction nécessite la version 1.19.4.

2023-03-05 17:41 UTC, Leirof approved these changes
Après un test, j'ai remarqué que la zone d'arrivée est décalée de 1 sur l'axe x par rapport à la valeur passée en paramètre

2023-03-05 17:42 UTC, Leirof requested changes
> Après un test, j'ai remarqué que la zone d'arrivée est décalée de 1 sur l'axe x par rapport à la valeur passée en paramètre

Mauvais bouton

2023-03-05 17:43 UTC, Leirof commented
En mettant le radius a 0 c'est assez facile à s'en rendre compte

2023-03-05 21:41 UTC, A2va commented
J'ai fixé le quand le radius valait 0, mais j'ai trouvé un autre problème avec l'accuracy 10-3. Sur un carré de 3x3, l'entité ignore tous un côté du carré, alors que ce n'est pas le cas avec le spread version régulière.

2023-03-11 13:04 UTC, Leirof commented
J'ai encore des soucis avec la fonction : quand je l'utilise, le score `bs.in.2` ne semble pas être pris en compte (la fonction me téléporte à l'endroit indiqué par les scores `bs.in.0` et `bs.in.1`) et il est modifié lors de l'execution, mais pas remis à sa valeur avant l'execution.

Chose plus étonnante, la variatne accuracy/10-3 se comporte exactement de la même façon, avec les entrées qui semblent être interprétées en bloc et non en millibloc 🤔

2023-03-11 13:31 UTC, A2va commented on datapacks/Bookshelf/data/bs.location/functions/spread.mcfunction
> +scoreboard players add @s bs.loc.x 1
Pourquoi ajouter un bloc ? Ce changement fait que si l'on fixe un radius de 1, l'entité peut se déplacer de deux bloc par rapport au centre x et y.

2023-03-11 13:34 UTC, A2va commented
> J'ai encore des soucis avec la fonction : quand je l'utilise, le score bs.in.2 ne semble pas être pris en compte (la fonction me téléporte à l'endroit indiqué par les scores bs.in.0 et bs.in.1) et il est modifié lors de l’exécution, mais pas remis à sa valeur avant l’exécution.

J'ai pas tous compris. Quel score est modifié lors de l’exécution ?

2023-03-11 13:36 UTC, Leirof commented on datapacks/Bookshelf/data/bs.location/functions/spread.mcfunction
> +scoreboard players add @s bs.loc.x 1
D'après mes tests, lorsqu'on définit une position (x,z) et qu'on lance la fonction, on arrive en (x-0.5,z-0.5) au lieu de (x+0.5,z+0.5), soit (x-1,z-1) si on considère uniquement le bloc

Cela dit vu que j'ai eu d'autres soucis il y a moyen que ce soit un side effect des autres soucis

2023-03-11 13:37 UTC, Leirof commented
Durant mes tests j'ai set `bs.in.2` à 5 mais après l'execution de la fonction, il est retombé à 1 pour aucune raison apparente

2023-03-11 13:39 UTC, Leirof commented
Y'a peut être quelque chose que je fais mal mais là comme ça je vois pas (j'avoue ne pas avoir pris le temps de décortiquer le fonctionnement de la fonction), la doc que j'ai écrite te semble bonne ?

2023-03-11 13:40 UTC, A2va commented on datapacks/Bookshelf/data/bs.location/functions/spread.mcfunction
> +scoreboard players add @s bs.loc.x 1
Je vois, mais ce décalage est déjà gérer à la ligne 69: `execute at @s positioned over world_surface align xz run tp ~0.5 ~ ~0.5`.

2023-03-11 13:56 UTC, A2va commented
La doc est bien, je n'ai aucun problème avec. x)

Petit exemple vidéo (le centre est là ou est le block le plus haut):
https://user-images.githubusercontent.com/49582555/224488621-4730844a-cbe8-4809-a108-0ed050503da2.mp4

Je dois encore vérifier la fonction avec accuracy 10-30.

2023-03-11 17:44 UTC, Leirof approved these changes

2023-03-11 17:46 UTC, merged